[package]
name = "pogchat"
version = "0.2.0"
authors = ["Erin Nova <erin@the-system.eu.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
serde = "1.0.126"
serde_json = "1.0"
sha1 = "0.6.0"
